Popup branch
Metsanpeitto/Portfolio_1 pull request #12
Opened 2021-06-23 17:37 UTC by Metsanpeitto

# Portfolio: details popup window

- Use basic JavaScript syntax.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Understand how to parse a Figma design to create a UI.
- Use objects to store and access data.

2021-06-23 19:22 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @Metsanpeitto and @ntzwilly  , 

Excellent work with your javascript :+1:, 
You well-abstracted application logic and the dom-manipulation in your application. :clap: 
The projects section and modals dynamically generated with the javascript as expected. :star: 

I noticed only one small issue with the responsiveness of the modals. Please check the inline comment that I left. 

 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-23 19:22 UTC, sinansevgi commented on scss/layout/_modal.scss
> +          }
- [ ] This section has a responsiveness issue.

- In the mobile resolution (~380px), It doesn't fit its parent container and creates a vertical scroll bar.
![Mobile](https://user-images.githubusercontent.com/1642014/123150652-4a6a4600-d46b-11eb-933c-34285c283d29.png)

- In the desktop resolution(~1100px), It has non-visible parts.
![Desktop](https://user-images.githubusercontent.com/1642014/123150662-4c340980-d46b-11eb-9fd1-f6bbee93bfad.png)

I tested the project with firefox and chrome browsers. These issues occur on both of them. 

Suggestion: You can use [minmax](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax()) CSS function to for giving minimum sizes to your grid regions.

2021-06-24 08:42 UTC, Metsanpeitto commented on scss/layout/_modal.scss
> +          }
Thanks for pointing it out. I totally missed that when testing on my ends.
I have already fixed it and also added flex and flex-wrap to fix the 'technology bubbles' being chopped when the screen gets to the range between 320px and 380px.
Your critique was instructive and your suggestion helpful.
Thanks.

2021-06-24 09:20 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-06-24 10:12 UTC, merged