Alt history
Metsanpeitto/Portfolio_1 pull request #3
Opened 2021-06-04 19:42 UTC by Metsanpeitto

=======

## Request of code review 2 :pray: 

### This is the second time that I ask for a pull request for this same project.
 The first time I encounter a weird problem: 
  "_Enumerating objects: 26808, done.
Counting objects: 100% (26808/26808), done._"

 Find a workaround took me too many hours and I can't fix the old branch, and push it. It still
 I was told by a reviewer to don't delete repositories or branches from old pull requests and would happily upload the same branch as I did in the first request. However, I am not able to fix the old branch. It still is too large to be pushed. 

 Here a link to the old review  [""]  -  [https://github.com/Metsanpeitto/Portfolio_1/pull/2](https://github.com/Metsanpeitto/Portfolio_1/pull/2)

#Bellow the old Pull Request message

===================

### This is the final code that I have created :construction: for the Mobile Portfolio project.

- I exported the Figma files with the plugin 'Figma to Html'  :bullettrain_front:  in the same way I do when I design UI / UX.

- Also used SCSS :revolving_hearts: and created a folder structure to easily maintain or/and scale the project

- Includes simple animations :movie_camera: 

=======

⭐️ I hope you can understand.

2021-06-04 23:19 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @Metsanpeitto, 

Amazing work with the readme file and the pull request message. :1st_place_medal: 
Kudos for using SCSS :+1:

There are issues that you still need to work on to go further. :arrow_down: 

All professional developers will recommend that new developers start by first learning their fundamentals. This is very astute advice.  If you already have experience, It may seem boring to you. But they all relate as building blocks for almost every project we are going to build.
This project specifically designed to make you familiar with semantic HTML and prepare you for upcoming and more challenging projects. Therefore you should build every part of this project yourself. You shouldn't take the easy way out with the Figma export plugin.

- [ ] You should replace parts you took from the exported code. 

- Exported parts you used in the project made your code hard-to-read with machine-generated class names.
- Exported parts don't follow semantic HTML.


 ## Required Changes ♻️
_Please check the inline comments for my suggestions_ :arrow_down:


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-04 23:19 UTC, sinansevgi commented on README.md
>  # Portfolio: setup and mobile version skeleton
Kudos for descriptive readme :+1:

2021-06-04 23:19 UTC, sinansevgi commented on style.css
> +}
- [x] Image links are broken. Please fix them.

`..` dots represents the parent directory. But your CSS file and images folder in the same directory.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +      <div class="l-works">
- [x] You should use semantic HTML tags. You should use the `<section>` tag for the sections of your page.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +
- [x] You should use a list structure for the works section.

Grouping these section with `<li>` and `<ul>` will make your page more semantic, and it gives meaning to the HTML nodes, helping screen readers and other assistive technologies.


```html

<ul>
  <li>Tonic</li>
  <li>Multi-Post Stories </li>
  <li>Skills</li>
</ul>
```

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +            >
- [x] You should use `<p>` tag for block-level text elements.

`<span>` tag is an inline container to mark up a part of a text. It shouldn't be used as a block element.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +            >
- [x] You should use `<p>` tag for block-level text elements.
 
`<span>` tag is an inline container to mark up a part of a text. It shouldn't be used as a block element.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +            >
- [ ] You should use `<p>` tag for block-level text elements.
 
`<span>` tag is an inline container to mark up a part of a text. It shouldn't be used as a block element.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +            >
- [ ] You should use `<p>` tag for block-level text elements.
 
`<span>` tag is an inline container to mark up a part of a text. It shouldn't be used as a block element.

2021-06-04 23:19 UTC, sinansevgi commented on scss/components/_buttons.scss
> +  transition: all 0.9s cubic-bezier(0.86, 0, 0.07, 1);
- [ ] You should implement the button interactions also (Active, Hover, and Pressed).

Please check [the figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=37%3A2238) for the proper design.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +              </div>
- [ ] The list of project technologies should be a list `<ul>` and each of the technologies should be a list item `<li>`

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +              </div>
- [x] The list of project technologies should be a list `<ul>` and each of the technologies should be a list item `<li>`

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +              </div>
- [x] The list of project technologies should be a list `<ul>` and each of the technologies should be a list item `<li>`

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +              </div>
- [x] The list of project technologies should be a list `<ul>` and each of the technologies should be a list item `<li>`

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +          </div>
- [x] This section is not properly implemented. Images are not visible and styling is missing. Please check the screenshot below to see how it looks on my end. 
![Screen Shot 2021-06-05 at 01 22 45](https://user-images.githubusercontent.com/1642014/120868774-6f227a80-c59d-11eb-8ee8-0e3459667180.png)

Please check the figma template for proper design.

2021-06-04 23:19 UTC, sinansevgi commented on index.html
> +          </div>
- [x] The technology categories ("Languages", "Frameworks" and "Skills") should be in a list `<ul>`, each of them should be in a `<li>` list item.
- [x] The technologies listed under each category should be also list items.

Example structure:
```html

<ul>
  <li>Languages
    <ul>
      <li>JavaScript</li>
      <li>HTML</li>
      <li>CSS</li>
    </ul>
</li>
  <li>Frameworks </li>
  <li>Skills</li>
</ul>
```

2021-06-05 10:09 UTC, Metsanpeitto commented
=======

## The request of code review 3

This is the third time that I ask for a pull request for this same project.
===

### The first time I encounter a weird problem when pushing the branch to remote, it generated a conflict and I couldn't push the repository :
"Enumerating objects: 26808, done.
Counting objects: 100% (26808/26808), done."

===

### The second time I was pointed by the code reviewer to fix the following errors: 

- Image links are broken. (.. dots represents the parent directory. But your CSS file and images folder in the same directory.)
- Use semantic HTML tags. You should use the <section> tag for the sections of your page.
- You should use a list structure for the works section.
- You should use <p> tag for block-level text elements. (<span> tag is an inline container to mark up a part of a text. It shouldn't be used as a block element.)
- You should implement the button interactions also (Active, Hover, and Pressed).
- The list of project technologies should be a list <ul> and each of the technologies should be a list item <li>
- The 'experience' section is not properly implemented. Images are not visible and styling is missing. 

### Reflections
- All of the errors and suggestions above have been fixed for this pull request. 
- Linter and Stylelint show no errors.
- I search for any other thing that could make my code not good enough and fixed it before asking for this code review. 
- I downloaded the repository and tested it on my end as you would do. I found no errors.
- I didn't know that was not allowed to use Figma plugins to download the design. I understand the consequences and I don't go to do it again.
- In the future, I will allocate more time for possible debugging issues. This is my first week and after Wednesday the pace of the course accelerated in a surprising way. I did have problems catching up in just 2 days.

#Bellow the old Pull Request message

===================

This is the final code that I have created for construction for the Mobile Portfolio project.
I exported the Figma files with the plugin 'Figma to Html' bullettrain_front in the same way I do when I design UI / UX.

-Also used SCSS  and created a folder structure to easily maintain or/and scale the project

-Includes simple animations 

=======

:star: I hope you can understand. :pray:

2021-06-05 10:26 UTC, DeliceLydia commented on index.html
> +      <div class="l-works">
This was well addressed

2021-06-05 10:37 UTC, DeliceLydia commented on index.html
> +
Well addressed this!

2021-06-05 10:38 UTC, DeliceLydia commented on index.html
> +              </div>
Well addressed the issue

2021-06-05 10:39 UTC, DeliceLydia commented on index.html
> +              </div>
Well addressed this

2021-06-05 10:42 UTC, DeliceLydia commented on index.html
> +              </div>
well resolved

2021-06-05 10:42 UTC, DeliceLydia commented on index.html
> +          </div>
you fixed this. Good job!

2021-06-05 10:44 UTC, DeliceLydia commented on index.html
> +          </div>
Done this as well✔️

2021-06-05 10:51 UTC, DeliceLydia approved these changes
# Status: Approved ✔️

Hi, @Metsanpeitto, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional
- your project section is not centered on the mobile device I suggest that you do it before merging it can make it look good and make sure you correct all typo errors.
### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-05 14:21 UTC, merged